# Generated by Django 6.1.1 on 2026-09-19 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VersionERP",
            fields=[
                (
                    "version",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("creada", models.DateTimeField()),
                ("n_asientos", models.PositiveIntegerField()),
                ("lote2_cargado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "versión del ERP",
                "verbose_name_plural": "versiones del ERP",
                "ordering": ["-creada"],
            },
        ),
        migrations.CreateModel(
            name="SincronizacionERP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("ok", models.BooleanField()),
                ("n_asientos", models.PositiveIntegerField(default=0)),
                ("lote2_cargado", models.BooleanField(default=False)),
                ("peticiones", models.PositiveIntegerField(default=0)),
                ("reintentos_ora", models.PositiveIntegerField(default=0)),
                ("esperas_429", models.PositiveIntegerField(default=0)),
                ("relogins", models.PositiveIntegerField(default=0)),
                ("errores_red", models.PositiveIntegerField(default=0)),
                ("segundos", models.FloatField(default=0)),
                ("error", models.TextField(blank=True)),
                ("nuevos", models.PositiveIntegerField(default=0)),
                ("modificados", models.PositiveIntegerField(default=0)),
                ("eliminados", models.PositiveIntegerField(default=0)),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sincronizaciones",
                        to="panel.versionerp",
                    ),
                ),
            ],
            options={
                "verbose_name": "sincronización con el ERP",
                "verbose_name_plural": "sincronizaciones con el ERP",
                "ordering": ["-inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AsientoERP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asiento_id", models.CharField(max_length=20)),
                ("pedido", models.CharField(db_index=True, max_length=20)),
                ("proveedor_id", models.CharField(max_length=10)),
                ("nif", models.CharField(blank=True, max_length=12)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(max_length=12)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos",
                        to="panel.versionerp",
                    ),
                ),
            ],
            options={
                "verbose_name": "asiento del ERP",
                "verbose_name_plural": "asientos del ERP",
                "ordering": ["asiento_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "asiento_id"),
                        name="asiento_unico_por_version",
                    )
                ],
            },
        ),
    ]
