# Generated by Django 6.1.1 on 2026-09-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ejecucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(db_index=True, max_length=40)),
                ("norma", models.CharField(max_length=20)),
                ("version_erp", models.CharField(blank=True, max_length=16)),
                ("version_excel", models.CharField(blank=True, max_length=16)),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(default="en_curso", max_length=12)),
                ("hardware", models.JSONField(blank=True, default=dict)),
                ("resumen", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "ejecuciones",
                "ordering": ["-inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("file_id", models.CharField(max_length=255)),
                ("lote", models.CharField(max_length=40)),
                ("ok", models.BooleanField()),
                ("lector", models.CharField(blank=True, max_length=40)),
                ("metodo", models.CharField(max_length=20)),
                ("extraida", models.JSONField(blank=True, null=True)),
                ("intentos", models.JSONField(blank=True, default=list)),
                ("segundos", models.FloatField(default=0)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("coste_eur", models.FloatField(default=0)),
                ("modelo", models.CharField(blank=True, max_length=60)),
                ("creada", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creada"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(db_index=True, max_length=40)),
                ("file_id", models.CharField(max_length=255)),
                ("ruta", models.TextField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("bytes", models.PositiveIntegerField(default=0)),
                ("tipo", models.CharField(max_length=12)),
                ("paginas", models.PositiveIntegerField(default=0)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("primera_vez", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["lote", "file_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lote", "file_id"), name="documento_unico_por_lote"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.CharField(db_index=True, max_length=10)),
                ("motivo", models.TextField(blank=True)),
                ("pedido", models.CharField(blank=True, db_index=True, max_length=20)),
                ("metodo", models.CharField(blank=True, max_length=20)),
                ("outcome", models.JSONField(default=dict)),
                ("notas", models.JSONField(blank=True, default=list)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisiones",
                        to="panel.documento",
                    ),
                ),
                (
                    "ejecucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisiones",
                        to="panel.ejecucion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "decisiones",
                "ordering": ["documento__file_id"],
            },
        ),
        migrations.CreateModel(
            name="RevisionHumana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quien", models.CharField(max_length=150)),
                ("cuando", models.DateTimeField(auto_now_add=True)),
                ("resultado", models.CharField(max_length=10)),
                ("comentario", models.TextField(blank=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisiones",
                        to="panel.decision",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones",
                        to="panel.documento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "revisiones humanas",
                "ordering": ["-cuando"],
            },
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("ejecucion", "documento"),
                name="una_decision_por_documento_y_ejecucion",
            ),
        ),
    ]
