# Generated by Django 6.1.1 on 2026-09-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_ejecucion_lectura_documento_decision_revisionhumana_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("nif", models.CharField(max_length=12, unique=True)),
                ("iban", models.CharField(max_length=34)),
                ("ciudad", models.CharField(blank=True, max_length=80)),
                (
                    "condiciones_dias",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("revisar", models.BooleanField(default=False)),
                ("nota", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="panel.proveedor",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
    ]
