# Generated by Django 6.1.1 on 2026-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_ejecucion_lectura_documento_decision_revisionhumana_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectura",
            name="version",
            field=models.CharField(default="1", max_length=8),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="sha256",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="lectura",
            constraint=models.UniqueConstraint(
                fields=("sha256", "version"), name="lectura_por_contenido_y_version"
            ),
        ),
    ]
