# Generated by Django 6.1.1 on 2026-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="nif",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
