# Generated by Django 6.1.1 on 2026-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0005_proveedor_nif_extranjero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Importacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuando", models.DateTimeField(auto_now_add=True)),
                ("ficheros", models.CharField(max_length=255)),
                ("nuevos", models.PositiveIntegerField(default=0)),
                ("cambiados", models.PositiveIntegerField(default=0)),
                ("invalidos", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "importaciones",
                "ordering": ["-cuando", "-id"],
            },
        ),
    ]
