# Generated by Django 6.1.1 on 2026-09-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0005_proveedor_nif_extranjero"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionAsistente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuando", models.DateTimeField(auto_now_add=True)),
                ("tipo", models.CharField(max_length=40)),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("resultado", models.TextField(blank=True)),
                ("ok", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "acción del asistente",
                "verbose_name_plural": "acciones del asistente",
                "ordering": ["-cuando", "-id"],
            },
        ),
    ]
