# Generated by Django 6.1.1 on 2026-09-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0008_conversacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ajuste",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("valor", models.TextField(blank=True)),
                ("cambiado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ajuste",
                "verbose_name_plural": "ajustes",
            },
        ),
        migrations.AddField(
            model_name="sincronizacionerp",
            name="automatica",
            field=models.BooleanField(default=False),
        ),
    ]
