# Generated by Django 6.1.1 on 2026-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_proveedor_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuando", models.DateTimeField(auto_now_add=True)),
                ("texto", models.TextField()),
                ("respuesta", models.TextField(blank=True)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("segundos", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-cuando"],
            },
        ),
    ]
