# Generated by Django 6.1.1 on 2026-09-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0007_accionasistente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=60)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "conversación",
                "verbose_name_plural": "conversaciones",
                "ordering": ["-actualizada", "-id"],
            },
        ),
        migrations.AddField(
            model_name="pregunta",
            name="detalles",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="modelo",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="accionasistente",
            name="conversacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones",
                to="panel.conversacion",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="conversacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="panel.conversacion",
            ),
        ),
    ]
